name: "Moropo - Trigger Mobile App Test Run"
author: "Moropo Limited"
description: "Uses Moropo.com to execute a mobile app UI test"
inputs:
  scheduled_test_id:
    description: "Moropo Scheduled Test ID - find this in your scheduled test setup wizard"
    required: true
  app_secret:
    description: "Moropo App Secret Key - find this in your app in the Moropo dashboard"
    required: true
  expo_release_channel:
    description: "Expo Release Channel (optional) - requires Moropo-Expo integration setup. Tell Moropo to pull a new Expo update for this test run."
    required: false
  github_token:
    description: "GitHub access token (optional) - so that the action can comment on the PR with the test trigger feedback"
    required: false
    default: ${{ github.token }}
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: "check"
  color: "blue"
